import type { Database, Brand, ProductCard, MisaCard } from './types'

const now = () => new Date().toISOString()

const dustFry: Brand = {
  id: 'brand-dustfry',
  name: 'Dust & Fry',
  slug: 'dust-fry',
  slogan: 'Premium fried chicken.',
  footerText: 'Dust & Fry · Sisäinen tuotekortti · Ei jaettavaksi ulkopuolisille',
  colors: {
    primary: '#0d0b08',
    secondary: '#c9a15a',
    accent: '#c0392b',
    paper: '#faf7f0',
    text: '#17140f',
  },
  fontStyle: 'display',
  headingStyle: 'uppercase',
  cardStyle: 'bold',
  imageStyle: 'full-bleed',
  defaultTemplate: 'product',
  templates: ['product', 'kitchen', 'misa', 'allergen', 'compact', 'showcase'],
  version: '1.0',
  createdAt: now(),
}

const gyro: Brand = {
  id: 'brand-gyro',
  name: 'GYRÖ',
  slug: 'gyro',
  slogan: 'Modern Mediterranean gyros & döner.',
  footerText: 'GYRÖ · Tuotantokortti · versionhallinta Tuotekorttikoneessa',
  colors: {
    primary: '#12365c',
    secondary: '#2e75b6',
    accent: '#e8b23a',
    paper: '#fbfdff',
    text: '#0e1c2a',
  },
  fontStyle: 'sans',
  headingStyle: 'uppercase',
  cardStyle: 'minimal',
  imageStyle: 'rounded',
  defaultTemplate: 'product',
  templates: ['product', 'kitchen', 'misa', 'allergen', 'compact'],
  version: '1.0',
  createdAt: now(),
}

const baseMeta = {
  updatedBy: 'Seed',
  versions: [],
}

const products: ProductCard[] = [
  {
    id: 'prod-hot-honey',
    brandId: dustFry.id,
    kind: 'product',
    name: 'Hot Honey Burger',
    category: 'Burgerit',
    description:
      'Rapea kanafilee, hunajainen chilikastike ja suolakurkku briossisämpylässä. Talon tunnistetuote.',
    portionSize: '1 burgeri',
    portionWeight: '320 g',
    price: '14,90 €',
    cost: '3,85 €',
    ingredients: [
      { name: 'Briossisämpylä', amount: '1', unit: 'kpl' },
      { name: 'Kanafilee (marinoitu)', amount: '120', unit: 'g' },
      { name: 'Dust-jauhoseos', amount: '35', unit: 'g' },
      { name: 'Hot honey -kastike', amount: '25', unit: 'g' },
      { name: 'Suolakurkku', amount: '20', unit: 'g' },
      { name: 'DF-majoneesi', amount: '20', unit: 'g' },
    ],
    instructions:
      'Leivitä kanafilee Dust-seoksessa. Paista 175 °C rasvakeittimessä 4 min (sisälämpö 75 °C). Valuta ritilällä 30 s.',
    assembly:
      'Paahda sämpylä leikkuupinnoilta. Pohjalle DF-majo, kanafilee, hot honey reilusti pinnalle, suolakurkut, kansi.',
    serving: 'Tarjoile heti tarjottimella, leike kohti asiakasta. Servetti + kostea pyyhe.',
    storage: 'Kootaan tilauksesta, ei säilytetä koottuna.',
    shelfLife: 'Heti tarjoiltava',
    temperatures: 'Paisto 175 °C · sisälämpö min 75 °C',
    prepTime: '6 min',
    preps: 'Kanafileet marinointi 12 h. Hot honey ja DF-majo misoina.',
    equipment: 'Rasvakeitin, paistolämpömittari, ritilä',
    allergens: ['gluten', 'milk', 'egg', 'mustard'],
    diets: [],
    warnings: 'Sisältää tulista kastiketta.',
    owner: 'Keittiömestari',
    approver: 'J. Virtanen',
    version: '1.2',
    status: 'approved',
    updatedAt: now(),
    ...baseMeta,
  },
  {
    id: 'prod-dust-fry',
    brandId: dustFry.id,
    kind: 'product',
    name: 'Dust Fry',
    category: 'Lisukkeet',
    description: 'Talon maustetut ranskalaiset Dust-suolalla ja DF-majolla.',
    portionSize: '1 annos',
    portionWeight: '180 g',
    price: '5,90 €',
    cost: '0,95 €',
    ingredients: [
      { name: 'Ranskanperunat 9 mm', amount: '150', unit: 'g' },
      { name: 'Dust-suola', amount: '4', unit: 'g' },
      { name: 'DF-majoneesi', amount: '30', unit: 'g' },
    ],
    instructions: 'Paista 175 °C 3 min 30 s kullanruskeaksi. Ravista, mausta Dust-suolalla heti.',
    serving: 'Annospussiin tai koriin, majo dipiksi kylkeen.',
    temperatures: 'Paisto 175 °C',
    prepTime: '4 min',
    equipment: 'Rasvakeitin, maustekulho',
    allergens: ['egg', 'mustard'],
    diets: ['G', 'M'],
    owner: 'Vuoropäällikkö',
    approver: 'J. Virtanen',
    version: '1.0',
    status: 'approved',
    updatedAt: now(),
    ...baseMeta,
  },
  {
    id: 'prod-berlin-doner',
    brandId: gyro.id,
    kind: 'product',
    name: 'Berlin Döner',
    category: 'Dönerit',
    description:
      'Hiillostettua broileridöneriä, minttu-punakaalia, voipapuhummusta ja valkosipulikastiketta lämpimässä pitassa.',
    portionSize: '1 döner',
    portionWeight: '420 g',
    price: '13,50 €',
    cost: '3,20 €',
    ingredients: [
      { name: 'Pitaleipä', amount: '1', unit: 'kpl' },
      { name: 'Broileridöner', amount: '150', unit: 'g' },
      { name: 'Minttu-punakaali', amount: '60', unit: 'g' },
      { name: 'Voipapuhummus', amount: '50', unit: 'g' },
      { name: 'Valkosipulikastike', amount: '30', unit: 'g' },
      { name: 'Tomaattikuutio', amount: '30', unit: 'g' },
      { name: 'Punasipuli', amount: '15', unit: 'g' },
    ],
    instructions: 'Lämmitä pita parilalla 30 s/puoli. Döner veitseltä suoraan parilalta.',
    assembly:
      'Hummus pohjalle, kaali, döner, tomaatti ja sipuli, valkosipulikastike raidoiksi. Kääri puoliksi paperiin.',
    serving: 'Tarjoile telineessä paperikääreessä.',
    shelfLife: 'Heti tarjoiltava',
    temperatures: 'Döner tarjoilulämpö min 60 °C',
    prepTime: '4 min',
    preps: 'Kaali ja hummus misoina, döner vartaassa.',
    equipment: 'Parila, dönerveitsi, käärepaperi',
    allergens: ['gluten', 'milk', 'sesame'],
    diets: [],
    owner: 'Keittiömestari',
    approver: 'M. Ali',
    version: '2.0',
    status: 'approved',
    updatedAt: now(),
    ...baseMeta,
  },
]

const misas: MisaCard[] = [
  {
    id: 'misa-df-majo',
    brandId: dustFry.id,
    kind: 'misa',
    name: 'DF-majoneesi',
    usedIn: 'Hot Honey Burger, Dust Fry, DF-nuggetit',
    yieldAmount: '1,1 kg',
    ingredients: [
      { name: 'Majoneesi', amount: '1', unit: 'kg' },
      { name: 'Valkosipuli (hienonnettu)', amount: '80', unit: 'g' },
      { name: 'Persilja', amount: '20', unit: 'g' },
      { name: 'Sitruunamehu', amount: '30', unit: 'g' },
      { name: 'Suola', amount: '12', unit: 'g' },
    ],
    instructions:
      'Hienonna valkosipuli ja persilja. Sekoita kaikki ainekset tasaiseksi. Maista — säädä suola ja sitruuna.',
    container: 'GN 1/6 kannella',
    storageTemp: '+2…+4 °C',
    shelfLife: '4 vrk',
    dating: 'Tarra: valmistuspäivä + viimeinen käyttöpäivä + tekijä',
    dosing: 'Burgeri 20 g · dippi 30 g',
    allergens: ['egg', 'mustard'],
    owner: 'Aamuvuoro',
    version: '1.1',
    status: 'approved',
    updatedAt: now(),
    ...baseMeta,
  },
  {
    id: 'misa-red-cabbage',
    brandId: gyro.id,
    kind: 'misa',
    name: 'Minttu-punakaali',
    usedIn: 'Berlin Döner, GYRÖ-lautanen, falafelpita',
    yieldAmount: '3 kg',
    ingredients: [
      { name: 'Punakaali (ohut suikale)', amount: '2,5', unit: 'kg' },
      { name: 'Tuore minttu', amount: '40', unit: 'g' },
      { name: 'Sitruunamehu', amount: '120', unit: 'g' },
      { name: 'Oliiviöljy', amount: '80', unit: 'g' },
      { name: 'Suola', amount: '25', unit: 'g' },
      { name: 'Sokeri', amount: '15', unit: 'g' },
    ],
    instructions:
      'Suikaloi kaali mandoliinilla. Nypi ja hienonna minttu. Sekoita kaikki, purista käsin 2 min, anna maustua 30 min kylmässä.',
    container: 'GN 1/3 kannella',
    storageTemp: '+2…+4 °C',
    shelfLife: '3 vrk',
    dating: 'Tarra: valmistuspäivä + klo + tekijä',
    dosing: 'Döner 60 g · lautanen 80 g',
    allergens: [],
    allergensUnknown: false,
    notApplicable: ['allergens'],
    owner: 'Kylmäkkö',
    version: '1.0',
    status: 'approved',
    updatedAt: now(),
    ...baseMeta,
  },
  {
    id: 'misa-butterbean',
    brandId: gyro.id,
    kind: 'misa',
    name: 'Voipapuhummus',
    usedIn: 'Berlin Döner, mezelautanen',
    yieldAmount: '2 kg',
    ingredients: [
      { name: 'Voipavut (keitetty)', amount: '1,4', unit: 'kg' },
      { name: 'Tahini', amount: '200', unit: 'g' },
      { name: 'Sitruunamehu', amount: '120', unit: 'g' },
      { name: 'Valkosipuli', amount: '30', unit: 'g' },
      { name: 'Jäävesi', amount: '150', unit: 'g' },
      { name: 'Suola', amount: '18', unit: 'g' },
      { name: 'Jeera', amount: '6', unit: 'g' },
    ],
    instructions:
      'Aja kaikki paitsi vesi sileäksi kutterissa 2 min. Valuta jäävesi joukkoon ajon aikana — rakenne kuohkea ja kiiltävä.',
    container: 'GN 1/3 kannella, pinta tasoitettuna + loraus öljyä',
    storageTemp: '+2…+4 °C',
    shelfLife: '3 vrk',
    dating: 'Tarra: valmistuspäivä + viimeinen käyttöpäivä',
    dosing: 'Döner 50 g · meze 90 g',
    allergens: ['sesame'],
    owner: 'Kylmäkkö',
    version: '1.0',
    status: 'review',
    updatedAt: now(),
    ...baseMeta,
  },
]

export function seedDatabase(): Database {
  return {
    brands: [dustFry, gyro],
    products,
    misas,
    audit: [
      {
        id: 'audit-seed',
        at: now(),
        by: 'Seed',
        action: 'seed',
        target: 'database',
        detail: 'Testidata luotu: Dust & Fry, GYRÖ + 6 korttia',
      },
    ],
    exports: [],
  }
}
